# Generated by Django 6.0 on 2025-12-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnsphere', '0003_vulnerabilitytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='environment',
        ),
    ]
